### ISSUE TITLE
Botón limpiar datos no limpia estados ni alfabeto

### ISSUE THREAD

**Issue by davideliseo** [davideliseo/grafos-t3#5]
Introducido en cbf6ab2910d92f376932d74a5f4913f4be8ed280.

**Comment by matias-rojas-dev** [comment]
Solución:
se integra nueva props "data (bool)" con valor inicial de false. Al momento de setear los valores, esta pasa a ser true, de manera que se envía como props a los componentes States y Alpahet. Estos componentes quedan con el siguiente condicional: 
![112](https://user-images.githubusercontent.com/69127196/123479255-aa2d3200-d5ce-11eb-973e-b40f73429f5f.PNG)
De manera que se muestra en el front de la siguiente forma:
![Save](https://user-images.githubusercontent.com/69127196/123478998-44d94100-d5ce-11eb-8443-98a41bcbf15f.PNG)

**Comment by davideliseo** [comment]
Funciona, pero hay un puro detalle. Si limpias los campos, y después agregas estados, se guardan, pero no se muestran en el InputDialog.

**Comment by davideliseo** [comment]
> Funciona, pero hay un puro detalle. Si limpias los campos, y después agregas estados, se guardan, pero no se muestran en el InputDialog.

Solucionado en bade400437dc7ea5ffd4e110b80c74c9488c7e45, refactorizando los subcomponentes del Automaton (States, Initial, Alphabet, etc.) con `useReducer` y custom hooks para eliminar los estados duplicados entre ellos y Automaton. 

A las finales, era muy díficil manejar el flujo de datos entre los componentes padres e hijos (y los hijos de ellos) hacia ambos lados.
